//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DMViewer.rc
//
#define IDD_ABOUTBOX                    100
#define ID_POPUP_LINKS_SPHERICAL        101
#define IDD_CONFIG_CAMERA               101
#define ID_POPUP_ADD_CHILD              102
#define ID_POPUP_DELETE                 103
#define ID_POPUP_LINKS_MOBILE_BASE      104
#define ID_POPUP_LINKS_PRISMATIC        105
#define ID_POPUP_LINKS_REVOLUTE         106
#define ID_POPUP_LINKS_STATIC_ROOT      107
#define ID_POPUP_LINKS_ZSCREW_TX        108
#define ID_POPUP_SIBLING_LINKS_MOBILE_BASE 109
#define ID_POPUP_SIBLING_LINKS_PRISMATIC 110
#define ID_POPUP_SIBLING_LINKS_REVOLUTE 111
#define ID_POPUP_SIBLING_LINKS_SPHERICAL 112
#define ID_POPUP_SIBLING_LINKS_STATIC_ROOT 113
#define ID_POPUP_SIBLING_LINKS_ZSCREW_TX 114
#define ID_POPUP_DELETE_RECURSIVELY     115
#define ID_POPUP_SEC_JOINT_REVOLUTE     116
#define ID_POPUP_SEC_JOINT_PRISMATIC    117
#define ID_POPUP_SEC_JOINT_SPHERICAL    118
#define ID_POPUP_SEC_JOINT_DELETE       119
#define ID_POPUP_SEC_JOINT_PROPERTIES   120
#define ID_POPUP_COPYLINK               121
#define ID_POPUP_PASTELINKASCHILD       122
#define ID_POPUP_CUTLINK                123
#define ID_POPUP_PASTELINKASSIBLING     124
#define ID_POPUP_PASTELINKASPARENT      125
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_DMVIEWTYPE                  129
#define IDB_IMAGELIST                   130
#define IDR_POPUP                       132
#define IDD_MOBILE_BASE_LINK_PROPERTIES 133
#define IDD_RIGID_BODY_DATA             134
#define IDD_CONTACT_POSITION            135
#define IDD_LINK_DATA                   136
#define IDD_OBJECT_DATA                 137
#define IDD_REVOLUTE_LINK_PROPERTIES    138
#define IDD_MDH_LINK_DATA               139
#define IDI_ICON_THETA                  142
#define IDI_ICON_ALPHA                  143
#define IDD_ACTUATOR_DATA               144
#define IDD_REV_DC_MOTOR_DATA           146
#define IDD_ZSCREW_TX_LINK_DATA         147
#define IDD_ARTICULATION_DATA           148
#define IDD_MOBILE_BASE_LINK_DATA       149
#define IDD_LINK_DATA_PP                150
#define IDR_TB_TREE_FUNCTIONS           151
#define IDB_BITMAP_REVOLUTE_LINK        155
#define IDB_BITMAP_MOBILE_BASE_LINK     156
#define IDB_BITMAP_ZSCREW_TX_LINK       157
#define IDB_BITMAP_PRISMATIC_LINK       158
#define IDB_BITMAP_SPHERICAL_LINK       159
#define IDB_BITMAP_STATIC_ROOT_LINK     160
#define IDD_SPHERICAL_LINK_DATA         161
#define IDD_ENVIRONMENT_DATA            162
#define IDD_SIMULATTION_DATA            163
#define IDC_CURSOR1                     164
#define IDD_SETUP_PATHS                 165
#define IDB_BITMAP_SEC_REVOLUTE_JOINT   166
#define IDB_BITMAP_SEC_PRISMATIC_JOINT  167
#define IDB_BITMAP_SEC_SPHERICAL_JOINT  168
#define IDD_SECONDARY_JOINT_DATA        170
#define IDD_SEC_SPHERICAL_JOINT_DATA    171
#define IDD_SEC_PRISMATIC_JOINT_DATA    172
#define IDD_SEC_REVOLUTE_JOINT_DATA     173
#define IDD_NODISPLAYMODE_STATUS        175
#define IDD_CONVEYOR_DATA               176
#define IDD_ENV_CONVEYOR_DATA           176
#define IDD_ENV_TREADMILL_DATA          176
#define IDD_ENV_TRIANGULATED_DATA       177
#define IDD_ENV_TERRAIN_DATA            177
#define IDD_COVERING                    178
#define IDD_ENV_DETAILS_FILE_SAVE       180
#define IDD_WORKSPACE_DATA              181
#define IDD_CAMERA_CONTROL              184
#define IDB_BITMAP1                     186
#define IDD_SIMULATION_DATA             187
#define IDD_CONFIG_SIMULATION           188
#define IDD_CONFIG_FILES                189
#define IDD_CONFIG_AXES                 190
#define IDD_CONFIG_BACKGROUND           191
#define IDC_EDIT_MOBILE_BASE_LINK_NAME  1000
#define IDC_EDIT_LINK_NAME              1000
#define IDC_BUTTON_BROWSE               1001
#define IDC_EDIT_MODEL_PATH             1002
#define IDC_EDIT_ARTICULATION_PATH      1003
#define IDC_EDIT_ENVIRONMENT_PATH       1004
#define IDC_EDIT_QUAT1                  1005
#define IDC_EDIT_CONTROL_DLL_PATH       1005
#define IDC_EDIT_QUAT2                  1006
#define IDC_EDIT_QUAT3                  1007
#define IDC_EDIT_QUAT4                  1008
#define IDC_EDIT_POS1                   1009
#define IDC_EDIT_POS2                   1011
#define IDC_EDIT_POS3                   1012
#define IDC_EDIT_VEL1                   1013
#define IDC_EDIT_VEL2                   1014
#define IDC_EDIT_VEL3                   1015
#define IDC_EDIT_VEL4                   1016
#define IDC_EDIT_VEL5                   1017
#define IDC_EDIT_VEL6                   1018
#define IDC_STATIC_RIGID_BODY_RECT      1024
#define IDC_BUTTON_ADD_CONTACT          1027
#define IDC_EDIT_POS_X                  1028
#define IDC_EDIT_POS_Y                  1029
#define IDC_EDIT_POS_Z                  1030
#define IDC_LIST_CONTACTS               1034
#define IDC_BUTTON_EDIT_CONTACT         1035
#define IDC_BUTTON_DELETE_CONTACT       1036
#define IDC_EDIT_MASS                   1037
#define IDC_EDIT_CENTER_GRAVITY_X       1038
#define IDC_EDIT_CENTER_GRAVITY_Y       1039
#define IDC_EDIT_CENTER_GRAVITY_Z       1040
#define IDC_EDIT_INERTIA_11             1041
#define IDC_EDIT_INERTIA_12             1042
#define IDC_EDIT_JOINT_FRICTION         1042
#define IDC_EDIT_INERTIA_13             1043
#define IDC_STATIC_LINK_RECT            1043
#define IDC_EDIT_INERTIA_21             1044
#define IDC_STATIC_OBJECT_DATA_RECT     1044
#define IDC_EDIT_INERTIA_22             1045
#define IDC_EDIT_MDH_A                  1045
#define IDC_EDIT_INERTIA_23             1046
#define IDC_EDIT_MDH_ALPHA              1046
#define IDC_EDIT_INERTIA_31             1047
#define IDC_EDIT_MDH_D                  1047
#define IDC_EDIT_INERTIA_32             1048
#define IDC_EDIT_MDH_THETA              1048
#define IDC_EDIT_INERTIA_33             1049
#define IDC_EDIT_JOINT_MINIMUM          1049
#define IDC_EDIT_JOINT_MAXIMUM          1050
#define IDC_EDIT_JOINT_SPRING           1051
#define IDC_EDIT_JOINT_DAMPER           1052
#define IDC_EDIT_STATE_Q                1053
#define IDC_EDIT_STATE_DQ               1054
#define IDC_COMBO_ACTUATOR_TYPE         1054
#define IDC_EDIT_TORQUE_CONSTANT        1055
#define IDC_EDIT_BACK_EMF_CONSTANT      1056
#define IDC_EDIT_ARMATURE_RESISTANCE    1057
#define IDC_EDIT_ROTOR_INERTIA          1058
#define IDC_EDIT_COULOMB_FRICTION_CONSTANT 1059
#define IDC_EDIT_HALF_DROP_VALUE        1060
#define IDC_EDIT_VISCOUS_FRICTION_CONSTANT 1061
#define IDC_EDIT_MAXIMUM_DROP_VALUE     1062
#define IDC_STATIC_ACTUATOR_TYPE_DATA_RECT 1063
#define IDC_EDIT_GEAR_RATIO             1063
#define IDC_STATIC_ACTUATOR_TYPE        1064
#define IDC_COMBO1                      1065
#define IDC_STATIC_TOOLBAR_RECT         1066
#define IDC_EDIT_JOINT_OFFSET_X         1067
#define IDC_EDIT_JOINT_OFFSET_Y         1068
#define IDC_EDIT_JOINT_OFFSET_Z         1069
#define IDC_EDIT_INITIAL_JOINT_ANGLE_1  1070
#define IDC_EDIT_INITIAL_ANGULAR_VELOCITY_X 1071
#define IDC_EDIT_AXES_LIMIT_X           1072
#define IDC_EDIT_INITIAL_JOINT_ANGLE_2  1073
#define IDC_EDIT_INITIAL_JOINT_ANGLE_3  1074
#define IDC_EDIT_INITIAL_ANGULAR_VELOCITY_Y 1075
#define IDC_EDIT_INITIAL_ANGULAR_VELOCITY_Z 1076
#define IDC_EDIT_AXES_LIMIT_Y           1077
#define IDC_EDIT_AXES_LIMIT_Z           1078
#define IDC_EDIT_SPRING_CONSTANT        1079
#define IDC_EDIT_DAMPER_CONSTANT        1080
#define IDC_EDIT_GRAVITY_X              1081
#define IDC_EDIT_GRAVITY_Y              1082
#define IDC_EDIT_GRAVITY_Z              1083
#define IDC_EDIT_NORMAL_SPRING_CONSTANT 1084
#define IDC_EDIT_PLANAR_SPRING_CONSTANT 1085
#define IDC_EDIT_PLANAR_DAMPER_CONSTANT 1086
#define IDC_EDIT_NORMAL_DAMPER_CONSTANT 1087
#define IDC_EDIT_US                     1088
#define IDC_EDIT_UK                     1089
#define IDC_EDIT_TERRAIN_FILE           1090
#define IDC_EDIT_DETAILS_FILE           1090
#define IDC_BUTTON_TERRAIN_BROWSE       1091
#define IDC_EDIT_STEP_SIZE              1092
#define IDC_EDIT_DISPLAY_RATE           1093
#define IDC_EDIT_ARTICULATION_FILE      1094
#define IDC_EDIT_CONTROL_FILE           1095
#define IDC_BUTTON_MODEL_PATH           1095
#define IDC_EDIT_ENVIRONMENT_FILE       1096
#define IDC_BUTTON_ARTICULATION_PATH    1096
#define IDC_BUTTON_ENVIRONMENT_PATH     1097
#define IDC_BUTTON_CONTROL_DLL_PATH     1098
#define IDC_EDIT_A_POSITION1            1098
#define IDC_EDIT_A_POSITION2            1099
#define IDC_EDIT_A_POSITION3            1100
#define IDC_EDIT_A_ROTATION11           1101
#define IDC_EDIT_A_ROTATION12           1102
#define IDC_EDIT_A_ROTATION13           1103
#define IDC_COMBO_LINK_A                1104
#define IDC_EDIT_A_ROTATION21           1107
#define IDC_EDIT_LINEAR_CONSTRAINT_DAMPER 1107
#define IDC_EDIT_A_ROTATION22           1108
#define IDC_EDIT_LINEAR_CONSTRAINT_SPRING 1108
#define IDC_EDIT_A_ROTATION23           1109
#define IDC_EDIT_ANGULAR_CONSTRAINT_DAMPER 1109
#define IDC_EDIT_A_ROTATION31           1110
#define IDC_EDIT_ANGULAR_CONSTRAINT_SPRING 1110
#define IDC_EDIT_A_ROTATION32           1111
#define IDC_EDIT_A_ROTATION33           1112
#define IDC_COMBO_STABILIZATION         1116
#define IDC_COMBO_JOINT_TYPE            1117
#define IDC_STATIC_SIMULATION_TIME      1117
#define IDC_EDIT_NORMAL_DIRECTION_X     1118
#define IDC_EDIT1                       1119
#define IDC_EDIT_FILENAME               1119
#define IDC_EDIT_EULER_STEP_SIZE        1119
#define IDC_EDIT_X_DIM                  1119
#define IDC_EDIT_OFFSET_X               1119
#define IDC_EDIT_NORMAL_DIRECTION_Y     1120
#define IDC_EDIT_RK4_STEP_SIZE          1120
#define IDC_EDIT_OFFSET_Y               1120
#define IDC_EDIT_WIREFRAME_LN_WIDTH     1120
#define IDC_EDIT_NORMAL_DIRECTION_Z     1121
#define IDC_EDIT_OFFSET_Z               1121
#define IDC_BUTTON_OPEN                 1122
#define IDC_EDIT_OFFSET_X2              1122
#define IDC_EDIT_VIEWANGLE_DEG          1122
#define IDC_EDIT_WIREFRAME_ELEVATION    1122
#define IDC_BUTTON_SAVE_AS              1123
#define IDC_BUTTON_SAVE                 1124
#define IDC_EDIT_VELOCITY_DIRECTION_X   1125
#define IDC_EDIT_VELOCITY_DIRECTION_Y   1126
#define IDC_COMBO_LINK_B                1127
#define IDC_EDIT_VELOCITY_DIRECTION_Z   1127
#define IDC_EDIT_B_POSITION1            1128
#define IDC_EDIT_VELOCITY_MAGNITUDE     1128
#define IDC_EDIT_B_POSITION2            1129
#define IDC_EDIT_POSITION_X             1129
#define IDC_EDIT_B_POSITION3            1130
#define IDC_EDIT_POSITION_Y             1130
#define IDC_EDIT_B_ROTATION11           1131
#define IDC_EDIT_POSITION_Z             1131
#define IDC_EDIT_B_ROTATION12           1132
#define IDC_EDIT_LENGTH                 1132
#define IDC_EDIT_B_ROTATION13           1133
#define IDC_EDIT_WIDTH                  1133
#define IDC_EDIT_B_ROTATION21           1134
#define IDC_RADIO_TYPE_COLOR            1134
#define IDC_EDIT_B_ROTATION22           1135
#define IDC_BUTTON_COLOR_EXAMPLE        1135
#define IDC_EDIT_B_ROTATION23           1136
#define IDC_BUTTON2                     1136
#define IDC_BUTTON_WIREFRAME_COLOR      1136
#define IDC_EDIT_B_ROTATION31           1137
#define IDC_RADIO2                      1137
#define IDC_RADIO_EXAMINE               1137
#define IDC_EDIT_B_ROTATION32           1138
#define IDC_EDIT_TEXTURE                1138
#define IDC_EDIT_B_ROTATION33           1139
#define IDC_STATIC_ENV_DETAILS_RECT     1140
#define IDC_RADIO_TRIANGULATED          1142
#define IDC_RADIO_TERRAIN               1142
#define IDC_RADIO_CONVEYOR              1143
#define IDC_RADIO_TREADMILL             1143
#define IDC_BUTTON1                     1144
#define IDC_BUTTON_ROLLER_COVERING      1144
#define IDC_BUTTON_EDIT_DETAILS         1144
#define IDC_BUTTON_LOAD_CURRENT_COI     1144
#define IDC_BUTTON_HELP                 1144
#define IDC_CHECK_REAL_TIME             1145
#define IDC_RADIO_PLACEMENT             1146
#define IDC_RADIO_EULER                 1147
#define IDC_RADIO_RK4                   1148
#define IDC_RADIO_RK45                  1149
#define IDC_EDIT_RK45_EPSILON           1150
#define IDC_EDIT_RK45_MINIMUM_STEP_SIZE 1151
#define IDC_LIST_ART_AND_CONTROL        1153
#define IDC_EDIT_Y_DIM                  1156
#define IDC_EDIT_GRID_RESOLUTION        1157
#define IDC_EDIT_XGRID_RESOLUTION       1157
#define IDC_EDIT_X_INDEX                1158
#define IDC_SPIN_X_INDEX                1159
#define IDC_EDIT_Y_INDEX                1160
#define IDC_SPIN_Y_INDEX                1161
#define IDC_EDIT_Z_VALUE                1162
#define IDC_RADIO_COLOR                 1163
#define IDC_EDIT_TEXTURE_FILE           1164
#define IDC_EDIT_YGRID_RESOLUTION       1165
#define IDC_BUTTON_CHOOSE_COLOR         1166
#define IDC_RADIO_TEXTURE               1167
#define IDC_BUTTON_APPLY_DEPTH          1168
#define IDC_BUTTON_CHOOSE_WIREFRAME_COLOR 1169
#define IDC_STATIC_DETAILS_FILE         1170
#define IDC_STATIC_DETAILS_TYPE         1171
#define IDC_EDIT_SIZE_X                 1172
#define IDC_STATIC_DETAILS_TYPE2        1172
#define IDC_EDIT_SIZE_Y                 1173
#define IDC_STATIC_GRAPHICS_MODEL_GROUP_BOX 1174
#define IDC_LINK_DYNAMECHS              1175
#define IDC_LINK_DRORIN                 1176
#define IDC_LINK_ROBOTBUILDER_WEBSITE   1176
#define IDC_LINK_HYPERLINK_CLASS        1177
#define IDC_EDIT_INERTIAL_AXES_WIDTH    1191
#define IDC_EDIT_INERTIAL_AXES_LENGTH   1192
#define IDC_EDIT_LINK_AXES_WIDTH        1193
#define IDC_EDIT_LINK_AXES_LENGTH       1194
#define IDC_RADIO_PAN                   1197
#define IDC_CHECK_INERTIAL              1198
#define IDC_CHECK_USE_VIEWPORT          1200
#define IDC_LINK_BUG_EMAIL              1202
#define IDC_LINK_DRORIN2                1203
#define IDC_SETINERTIALAXESASCOI        1205
#define IDC_EDIT_CENTER_OF_INTEREST     1206
#define IDC_BUTTON_RESET_COI            1207
#define IDC_BUTTON_RESET_CAMERA         1208
#define IDC_EDIT_COI_OFFSET_X           1209
#define IDC_EDIT_COI_OFFSET_Y           1210
#define IDC_EDIT_COI_OFFSET_Z           1211
#define IDC_USEYANDZ                    1212
#define IDC_BUTTON_SET_CAMERA           1214
#define IDC_TAB_MAIN                    1215
#define IDC_CHECK_USE_INTERTIAL         1218
#define IDC_CHECK_USEYANDZ              1219
#define IDC_USEINERTIALZ                1221
#define IDC_CHECK_WIREFRAME_OVERLAY     1225
#define ID_POPUP_PARENT_LINKS_REVOLUTE  15000
#define ID_POPUP_PARENT_LINKS_PRISMATIC 15001
#define ID_POPUP_PARENT_LINKS_MOBILE_BASE 15002
#define ID_POPUP_PARENT_LINKS_SPHERICAL 15003
#define ID_POPUP_PARENT_LINKS_ZSCREW_TX 15004
#define ID_POPUP_PARENT_LINKS_STATIC_ROOT 15005
#define ID_POPUP_SHOWAXES               15006
#define ID_POPUP_CAMERA_COI             15007
#define ID_POPUP_PROPERTIES             32772
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_BUTTON32777                  32777
#define ID_BUTTON_PLAY                  32778
#define ID_BUTTON_PAUSE                 32779
#define ID_BUTTON_STATE                 32780
#define ID_VIEW_TOGGLESTATE             32781
#define ID_BUTTON_STOP                  32782
#define ID_ENVIRONMENT_OPENENVIRONMENTFILE 32784
#define ID_ENVIRONMENT_EDITENVIRONMENTPROPERITIES 32785
#define ID_ENVIRONMENT_NEWENVIRONMENTFILE 32786
#define ID_ENVIRONMENT_SAVEENVIRONMENT  32787
#define ID_ENVIRONMENT_SAVEENVIRONMENTAS 32788
#define ID_ARTICULATION_NEWARTICULATIONFILE 32789
#define ID_ARTICULATION_OPENARTICULATIONFILE 32790
#define ID_ARTICULATION_SAVEARTICULATIONFILE 32791
#define ID_ARTICULATION_SAVEARTICULATIONFILEAS 32792
#define ID_CONTROL_SELECTCONTROLDLL     32794
#define ID_BUTTON_VIEW_FRONT            32797
#define ID_BUTTON_VIEW_RIGHT            32798
#define ID_BUTTON_VIEW_BACK             32799
#define ID_BUTTON_VIEW_LEFT             32800
#define ID_BUTTON_VIEW_BOTTOM           32801
#define ID_BUTTON_VIEW_TOP              32802
#define ID_BUTTON_TOGGLE_AXES           32803
#define ID_BUTTON_ZOOM_IN               32805
#define ID_BUTTON_ZOOM_OUT              32806
#define ID_CFGFILE_EDITSIMULATIONPROPERTIES 32807
#define ID_SETUP_DEFAULTPATHS           32808
#define ID_ARTICULATION_NEWCLOSEDARTICULATION 32809
#define ID_SETUP_NODISPLAYMODEDURINGSIMULATION 32811
#define ID_SETUP_WORKSPACESETUP         32817
#define ID_PLAYBACK_OPENPLAYBACKFILE    32818
#define ID_PLAYBACK_SAVEPLAYBACK        32819
#define ID_PLAYBACK_SAVEPLAYBACKFILEAS  32820
#define ID_BUTTON_RECORD                32823
#define ID_BUTTON_PLAYBACK              32826
#define ID_BUTTON32827                  32827
#define ID_BUTTON_BUILD                 32832
#define ID_BUTTON_SHOW_LINK_AXES        32835
#define ID_BUTTON_HIDE_LINK_AXES        32838
#define ID_VIEW_CAMERACONTROL           32848
#define ID_BUTTON_TEST3                 32849
#define ID_BUTTON_TEST4                 32850
#define ID_BUTTON_RBMODLER              32851
#define ID_VIEW_CAMERALIGHT             32852
#define ID_HELP_USERSGUIDE              32853
#define ID_BUTTON_REWIND                32854
#define ID_BUTTON_FASTFORWARD           32855
#define ID_BUTTON_SLOWMOTION            32856
#define ID_BUTTON_USERVIEW              32857
#define ID_BUTTONPAN                    32860
#define ID_BUTTONEXAMINE                32861
#define ID_HELP_TUTORIAL                32862
#define ID_VIEW_WIDEANGLE               32863
#define IDS_STRING_CONTACT_FORMAT       61204
#define IDS_STRING_OUT_OF_MEM_MSG       61205
#define ID_INDICATOR_SIM_TIME           61206
#define IDS_STRING_UNABLE_TO_LOCATE_COI 61207
#define IDS_STRING_INERTIAL_AXES        61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32864
#define _APS_NEXT_CONTROL_VALUE         1226
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
