areaName := dmGL

dependentMods :=

archSrc := \
	dmGLMouse.cpp \
	dmGLCamera.cpp \
	dmGLFlyCamera.cpp \
	dmGLPolarCamera.cpp \
	dmGLPolarCamera_zup.cpp \
	dmGLPolarCamera_yup.cpp


progSrc :=

GLUTLIB := 1

# -------------------------------------------------------------------------

ifeq ($(GLOBAL),true)
include make/arearules.mk
else
include ../make/local.mk
endif
