//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RBModeler.rc
//
#define IDD_ABOUTBOX                    100
#define ID_POPUP_ADD                    101
#define ID_POPUP_DELETE                 102
#define ID_POPUP_PROPERTIES             103
#define ID_POPUP_RENAME                 104
#define ID_POPUP_PRIMITIVE_SPHERE       105
#define ID_POPUP_PRIMITIVE_BLOCK        106
#define ID_POPUP_PRIMITIVE_CONE         107
#define ID_POPUP_PRIMITIVE_CYLINDER     108
#define ID_POPUP_PRIMITIVE_HEMISPHERE   109
#define ID_POPUP_PRIMITIVE_TRUNCATED_CONE 110
#define ID_POPUP_SHOWAXES               111
#define ID_POPUP_CAMERA_COI             112
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_RBMODLTYPE                  129
#define IDD_MOVEMENT_CONTROLS           130
#define IDB_IMAGELIST                   131
#define IDD_PRIMITIVE_SPHERE            132
#define IDD_COVERING                    133
#define IDB_PRIMITIVE_SPHERE            134
#define IDB_AXES                        135
#define IDD_PLACEMENT                   136
#define IDD_ROTATION_QUATERNION         138
#define IDD_ROTATION_EULER_ANGLES       139
#define IDD_ROTATION_ANGLE_AXIS         140
#define IDD_PRIMITIVE_BLOCK             141
#define IDD_PRIMITIVE_CONE              142
#define IDD_PRIMITIVE_CYLINDER          143
#define IDD_PRIMITIVE_HEMISPHERE        144
#define IDD_PRIMITIVE_TRUNCATED_CONE    145
#define IDB_PRIMITIVE_CYLINDER          146
#define IDB_PRIMITIVE_CONE              147
#define IDB_PRIMITIVE_TRUNCATED_CONE    148
#define IDB_PRIMITIVE_HEMISPHERE        149
#define IDB_PRIMITIVE_BLOCK             150
#define IDD_CENTER_OF_GRAVITY           151
#define IDD_PHYSICAL_PROPERTIES         152
#define IDD_INERTIA_TENSOR              155
#define IDD_LINK_PHYSICAL_PROPERTIES    156
#define IDD_CAMERA_CONTROL              184
#define IDC_EDIT_STEP_SIZE              1000
#define IDC_EDIT_RADIUS                 1001
#define IDC_EDIT_LATITUDE               1002
#define IDC_EDIT_LONGITUDE              1003
#define IDC_CHECK_BOTH_SIDES            1004
#define IDC_CHECK_GOURAUD               1005
#define IDC_RADIO_TYPE_COLOR            1007
#define IDC_RADIO_TEXTURE               1008
#define IDC_BUTTON_COLOR                1009
#define IDC_BUTTON_BROWSE               1011
#define IDC_EDIT_TEXTURE                1012
#define IDC_BUTTON_COLOR_EXAMPLE        1014
#define IDC_RADIO_TRANSLATE             1015
#define IDC_RADIO_ROTATE                1016
#define IDC_RADIO_SCALE                 1017
#define IDC_SPIN_STEP_SIZE              1018
#define IDC_BUTTON_X_POSITIVE           1022
#define IDC_BUTTON_X_NEGATIVE           1023
#define IDC_BUTTON_Y_POSITIVE           1024
#define IDC_BUTTON_Y_NEGATIVE           1026
#define IDC_BUTTON_Z_NEGATIVE           1027
#define IDC_BUTTON_Z_POSITIVE           1028
#define IDC_STATIC_COMBO_RECT           1029
#define IDC_EDIT_SCALE_X                1030
#define IDC_EDIT_SCALE_Y                1031
#define IDC_EDIT_SCALE_Z                1032
#define IDC_EDIT_TRANSLATION_X          1033
#define IDC_EDIT_TRANSLATION_Y          1034
#define IDC_EDIT_TRANSLATION_Z          1035
#define IDC_TAB_ROTATION                1036
#define IDC_EDIT_EULER_X                1039
#define IDC_EDIT_EULER_Y                1040
#define IDC_EDIT_EULER_Z                1041
#define IDC_EDIT_QUATERNION_1           1043
#define IDC_EDIT_QUATERNION_2           1044
#define IDC_EDIT_ANGLE                  1044
#define IDC_EDIT_QUATERNION_3           1045
#define IDC_EDIT_AXIS_X                 1045
#define IDC_EDIT_QUATERNION_4           1046
#define IDC_EDIT_AXIS_Y                 1046
#define IDC_EDIT_AXIS_Z                 1047
#define IDC_RADIO_SPATIAL_TRANSFORM     1048
#define IDC_EDIT_XLENGTH                1049
#define IDC_EDIT_YLENGTH                1050
#define IDC_EDIT_ZLENGTH                1051
#define IDC_EDIT_HEIGHT                 1052
#define IDC_EDIT_TESS                   1053
#define IDC_EDIT_BASE_RADIUS            1054
#define IDC_EDIT_TOP_RADIUS             1055
#define IDC_EDIT_CENTER_OF_GRAVITY_X    1056
#define IDC_EDIT_CENTER_OF_GRAVITY_Y    1057
#define IDC_EDIT_CENTER_OF_GRAVITY_Z    1058
#define IDC_EDIT_MASS                   1059
#define IDC_EDIT_INERTIA_TENSOR11       1061
#define IDC_EDIT_INERTIA_TENSOR12       1062
#define IDC_EDIT_INERTIA_TENSOR13       1063
#define IDC_EDIT_INERTIA_TENSOR21       1064
#define IDC_EDIT_INERTIA_TENSOR22       1065
#define IDC_EDIT_INERTIA_TENSOR23       1066
#define IDC_EDIT_INERTIA_TENSOR31       1067
#define IDC_EDIT_INERTIA_TENSOR32       1068
#define IDC_EDIT_INERTIA_TENSOR33       1069
#define IDC_EDIT_COG_X                  1073
#define IDC_EDIT_COG_Y                  1074
#define IDC_EDIT_COG_Z                  1075
#define IDC_CHECK_USE_USER_DATA         1075
#define IDC_EDIT_TOTAL_MASS             1076
#define IDC_EDIT_OFFSET_X               1119
#define IDC_EDIT_OFFSET_Y               1120
#define IDC_EDIT_OFFSET_Z               1121
#define IDC_RADIO_EXAMINE               1137
#define IDC_LINK_ROBOTBUILDER_WEBSITE   1176
#define IDC_LINK_HYPERLINK_CLASS        1177
#define IDC_RADIO_PAN                   1197
#define IDC_CHECK_INERTIAL              1198
#define IDC_CHECK_USE_VIEWPORT          1200
#define IDC_LINK_BUG_EMAIL              1202
#define IDC_USEINERTIALZ                1221
#define ID_PRIMITIVES_ADD_SPHERE        32771
#define ID_PRIMITIVES_ADD_BLOCK         32773
#define ID_PRIMITIVES_ADD_CONE          32774
#define ID_PRIMITIVES_ADD_CYLINDER      32775
#define ID_PRIMITIVES_ADD_HEMISPHERE    32776
#define ID_PRIMITIVES_ADD_TRUNCATEDCONE 32777
#define ID_BUTTON_VIEW_FRONT            32778
#define ID_BUTTON_VIEW_RIGHT            32779
#define ID_BUTTON_VIEW_BACK             32780
#define ID_BUTTON_VIEW_LEFT             32781
#define ID_BUTTON_VIEW_BOTTOM           32782
#define ID_BUTTON_VIEW_TOP              32783
#define ID_BUTTON_ZOOM_IN               32784
#define ID_BUTTON_ZOOM_OUT              32785
#define ID_PROPERTIES_CENTEROFGRAVITY   32787
#define ID_PROPERTIES_MOMENTOFINERTIA   32788
#define ID_BUTTON_SHOW_LOCAL_AXES       32790
#define ID_BUTTON_HIDE_LOCAL_AXES       32791
#define ID_BUTTON_TOGGLE_AXES           32792
#define ID_FILE_SETBACKGROUNDCOLOR      32793
#define ID_PROPERTIES_PHYSICALPROPERTIES 32794
#define ID_VIEW_CAMERALIGHT             32795
#define ID_HELP_USERSGUIDE              32796
#define ID_HELP_TUTORIAL                32797
#define ID_BUTTONPAN                    32798
#define ID_BUTTONEXAMINE                32799
#define ID_VIEW_CAMERACONTROL           32848
#define IDS_STRING_OUT_OF_MEM_MSG       61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
